controller_joint_names: ['', 'J1J', 'J2J', 'J3J', 'J4J', 'M1J', 'M2J', 'M3J', 'M4J', 'M5J', 'X1J', 'X2J', 'X3J', 'X4J', 'X5J', 'S1J', 'S2J', 'S3J', 'S4J', 'S5J', 'Z1J', 'Z2J', 'Z3J', 'Z4J', 'Z5J', 'W1J', 'W2J', 'W3J', 'W4J', 'W5J', ]
